/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAiChatRouteImport } from './routes/_authenticated/ai-chat'
import { Route as AuthenticatedAiReviewRouteImport } from './routes/_authenticated/ai-review'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedBuildHealthRouteImport } from './routes/_authenticated/build-health'
import { Route as AuthenticatedContentRouteImport } from './routes/_authenticated/content'
import { Route as AuthenticatedContentReviewRouteImport } from './routes/_authenticated/content-review'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedManufacturingOrdersRouteImport } from './routes/_authenticated/manufacturing-orders'
import { Route as AuthenticatedProductAgentRouteImport } from './routes/_authenticated/product-agent'
import { Route as AuthenticatedQuoteRequestsRouteImport } from './routes/_authenticated/quote-requests'
import { Route as AuthenticatedSupplierInventoryRouteImport } from './routes/_authenticated/supplier-inventory'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CatalogAzCodeRouteImport } from './routes/catalog/$azCode'
import { Route as CatalogsSlugRouteImport } from './routes/catalogs/$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin/api-keys'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminFamiliesRouteImport } from './routes/_authenticated/admin/families'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin/integrations'
import { Route as AuthenticatedAdminUnitsRouteImport } from './routes/_authenticated/admin/units'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAiChatHistoryRouteImport } from './routes/_authenticated/ai-chat/history'
import { Route as AuthenticatedAiStudioIndexRouteImport } from './routes/_authenticated/ai-studio/index'
import { Route as AuthenticatedAiStudioBulkRouteImport } from './routes/_authenticated/ai-studio/bulk'
import { Route as AuthenticatedAiStudioDatasheetsRouteImport } from './routes/_authenticated/ai-studio/datasheets'
import { Route as AuthenticatedAiStudioImagesRouteImport } from './routes/_authenticated/ai-studio/images'
import { Route as AuthenticatedAiStudioOptimizeRouteImport } from './routes/_authenticated/ai-studio/optimize'
import { Route as AuthenticatedAiStudioQuotesRouteImport } from './routes/_authenticated/ai-studio/quotes'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedApiCenterIndexRouteImport } from './routes/_authenticated/api-center/index'
import { Route as AuthenticatedApprovalsIndexRouteImport } from './routes/_authenticated/approvals/index'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets/index'
import { Route as AuthenticatedAssetsBulkUploadRouteImport } from './routes/_authenticated/assets/bulk-upload'
import { Route as AuthenticatedAssetsDuplicatesRouteImport } from './routes/_authenticated/assets/duplicates'
import { Route as AuthenticatedAssetsUnlinkedRouteImport } from './routes/_authenticated/assets/unlinked'
import { Route as AuthenticatedDuplicatesIndexRouteImport } from './routes/_authenticated/duplicates/index'
import { Route as AuthenticatedExportIndexRouteImport } from './routes/_authenticated/export/index'
import { Route as AuthenticatedImportIndexRouteImport } from './routes/_authenticated/import/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedPricingIndexRouteImport } from './routes/_authenticated/pricing/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products/$id'
import { Route as AuthenticatedProductsDashboardRouteImport } from './routes/_authenticated/products/dashboard'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products/new'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests/index'
import { Route as AuthenticatedRequestsIdRouteImport } from './routes/_authenticated/requests/$id'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers/index'
import { Route as AuthenticatedSuppliersIdRouteImport } from './routes/_authenticated/suppliers/$id'
import { Route as AuthenticatedAdminCatalogsIndexRouteImport } from './routes/_authenticated/admin/catalogs/index'
import { Route as AuthenticatedAdminCatalogsSlugRouteImport } from './routes/_authenticated/admin/catalogs/$slug'
import { Route as ApiAgentV1InternalApprovalRouteImport } from './routes/api/agent/v1/internal-approval'
import { Route as ApiAgentV1OrderStatusRouteImport } from './routes/api/agent/v1/order-status'
import { Route as ApiAgentV1ProductAgentRouteImport } from './routes/api/agent/v1/product-agent'
import { Route as ApiAgentV1QuoteRequestRouteImport } from './routes/api/agent/v1/quote-request'
import { Route as ApiAgentV1QuoteResponseRouteImport } from './routes/api/agent/v1/quote-response'
import { Route as ApiPublicV1AssetsRouteImport } from './routes/api/public/v1/assets'
import { Route as ApiPublicV1PricingRouteImport } from './routes/api/public/v1/pricing'
import { Route as ApiPublicV1ProductsRouteImport } from './routes/api/public/v1/products'
import { Route as ApiPublicV1SuppliersRouteImport } from './routes/api/public/v1/suppliers'
import { Route as ApiPrivateV1AiBatchOptimizeRouteImport } from './routes/api/private/v1/ai/batch-optimize'
import { Route as ApiPrivateV1AiGenerateDatasheetRouteImport } from './routes/api/private/v1/ai/generate-datasheet'
import { Route as ApiPrivateV1AiJobStatusRouteImport } from './routes/api/private/v1/ai/job-status'
import { Route as ApiPrivateV1AiOptimizeProductRouteImport } from './routes/api/private/v1/ai/optimize-product'
import { Route as ApiPublicV1AiQuotesRouteImport } from './routes/api/public/v1/ai/quotes'
import { Route as ApiPublicV1ProductsAzCodeRouteImport } from './routes/api/public/v1/products/$azCode'
import { Route as ApiPublicV1SuppliersWebhookRouteImport } from './routes/api/public/v1/suppliers/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiChatRoute = AuthenticatedAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiReviewRoute = AuthenticatedAiReviewRouteImport.update({
  id: '/ai-review',
  path: '/ai-review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuildHealthRoute =
  AuthenticatedBuildHealthRouteImport.update({
    id: '/build-health',
    path: '/build-health',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentRoute = AuthenticatedContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContentReviewRoute =
  AuthenticatedContentReviewRouteImport.update({
    id: '/content-review',
    path: '/content-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManufacturingOrdersRoute =
  AuthenticatedManufacturingOrdersRouteImport.update({
    id: '/manufacturing-orders',
    path: '/manufacturing-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductAgentRoute =
  AuthenticatedProductAgentRouteImport.update({
    id: '/product-agent',
    path: '/product-agent',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuoteRequestsRoute =
  AuthenticatedQuoteRequestsRouteImport.update({
    id: '/quote-requests',
    path: '/quote-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierInventoryRoute =
  AuthenticatedSupplierInventoryRouteImport.update({
    id: '/supplier-inventory',
    path: '/supplier-inventory',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogAzCodeRoute = CatalogAzCodeRouteImport.update({
  id: '/catalog/$azCode',
  path: '/catalog/$azCode',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsSlugRoute = CatalogsSlugRouteImport.update({
  id: '/catalogs/$slug',
  path: '/catalogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFamiliesRoute =
  AuthenticatedAdminFamiliesRouteImport.update({
    id: '/families',
    path: '/families',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUnitsRoute = AuthenticatedAdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAiChatHistoryRoute =
  AuthenticatedAiChatHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedAiChatRoute,
  } as any)
const AuthenticatedAiStudioIndexRoute =
  AuthenticatedAiStudioIndexRouteImport.update({
    id: '/ai-studio/',
    path: '/ai-studio/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiStudioBulkRoute =
  AuthenticatedAiStudioBulkRouteImport.update({
    id: '/ai-studio/bulk',
    path: '/ai-studio/bulk',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiStudioDatasheetsRoute =
  AuthenticatedAiStudioDatasheetsRouteImport.update({
    id: '/ai-studio/datasheets',
    path: '/ai-studio/datasheets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiStudioImagesRoute =
  AuthenticatedAiStudioImagesRouteImport.update({
    id: '/ai-studio/images',
    path: '/ai-studio/images',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiStudioOptimizeRoute =
  AuthenticatedAiStudioOptimizeRouteImport.update({
    id: '/ai-studio/optimize',
    path: '/ai-studio/optimize',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiStudioQuotesRoute =
  AuthenticatedAiStudioQuotesRouteImport.update({
    id: '/ai-studio/quotes',
    path: '/ai-studio/quotes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApiCenterIndexRoute =
  AuthenticatedApiCenterIndexRouteImport.update({
    id: '/api-center/',
    path: '/api-center/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApprovalsIndexRoute =
  AuthenticatedApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsBulkUploadRoute =
  AuthenticatedAssetsBulkUploadRouteImport.update({
    id: '/assets/bulk-upload',
    path: '/assets/bulk-upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsDuplicatesRoute =
  AuthenticatedAssetsDuplicatesRouteImport.update({
    id: '/assets/duplicates',
    path: '/assets/duplicates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsUnlinkedRoute =
  AuthenticatedAssetsUnlinkedRouteImport.update({
    id: '/assets/unlinked',
    path: '/assets/unlinked',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDuplicatesIndexRoute =
  AuthenticatedDuplicatesIndexRouteImport.update({
    id: '/duplicates/',
    path: '/duplicates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExportIndexRoute =
  AuthenticatedExportIndexRouteImport.update({
    id: '/export/',
    path: '/export/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportIndexRoute =
  AuthenticatedImportIndexRouteImport.update({
    id: '/import/',
    path: '/import/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingIndexRoute =
  AuthenticatedPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsDashboardRoute =
  AuthenticatedProductsDashboardRouteImport.update({
    id: '/products/dashboard',
    path: '/products/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsIdRoute = AuthenticatedRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuppliersIdRoute =
  AuthenticatedSuppliersIdRouteImport.update({
    id: '/suppliers/$id',
    path: '/suppliers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCatalogsIndexRoute =
  AuthenticatedAdminCatalogsIndexRouteImport.update({
    id: '/catalogs/',
    path: '/catalogs/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogsSlugRoute =
  AuthenticatedAdminCatalogsSlugRouteImport.update({
    id: '/catalogs/$slug',
    path: '/catalogs/$slug',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiAgentV1InternalApprovalRoute =
  ApiAgentV1InternalApprovalRouteImport.update({
    id: '/api/agent/v1/internal-approval',
    path: '/api/agent/v1/internal-approval',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentV1OrderStatusRoute = ApiAgentV1OrderStatusRouteImport.update({
  id: '/api/agent/v1/order-status',
  path: '/api/agent/v1/order-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentV1ProductAgentRoute = ApiAgentV1ProductAgentRouteImport.update({
  id: '/api/agent/v1/product-agent',
  path: '/api/agent/v1/product-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentV1QuoteRequestRoute = ApiAgentV1QuoteRequestRouteImport.update({
  id: '/api/agent/v1/quote-request',
  path: '/api/agent/v1/quote-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentV1QuoteResponseRoute = ApiAgentV1QuoteResponseRouteImport.update({
  id: '/api/agent/v1/quote-response',
  path: '/api/agent/v1/quote-response',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AssetsRoute = ApiPublicV1AssetsRouteImport.update({
  id: '/api/public/v1/assets',
  path: '/api/public/v1/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PricingRoute = ApiPublicV1PricingRouteImport.update({
  id: '/api/public/v1/pricing',
  path: '/api/public/v1/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProductsRoute = ApiPublicV1ProductsRouteImport.update({
  id: '/api/public/v1/products',
  path: '/api/public/v1/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SuppliersRoute = ApiPublicV1SuppliersRouteImport.update({
  id: '/api/public/v1/suppliers',
  path: '/api/public/v1/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivateV1AiBatchOptimizeRoute =
  ApiPrivateV1AiBatchOptimizeRouteImport.update({
    id: '/api/private/v1/ai/batch-optimize',
    path: '/api/private/v1/ai/batch-optimize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPrivateV1AiGenerateDatasheetRoute =
  ApiPrivateV1AiGenerateDatasheetRouteImport.update({
    id: '/api/private/v1/ai/generate-datasheet',
    path: '/api/private/v1/ai/generate-datasheet',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPrivateV1AiJobStatusRoute = ApiPrivateV1AiJobStatusRouteImport.update({
  id: '/api/private/v1/ai/job-status',
  path: '/api/private/v1/ai/job-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivateV1AiOptimizeProductRoute =
  ApiPrivateV1AiOptimizeProductRouteImport.update({
    id: '/api/private/v1/ai/optimize-product',
    path: '/api/private/v1/ai/optimize-product',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1AiQuotesRoute = ApiPublicV1AiQuotesRouteImport.update({
  id: '/api/public/v1/ai/quotes',
  path: '/api/public/v1/ai/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProductsAzCodeRoute =
  ApiPublicV1ProductsAzCodeRouteImport.update({
    id: '/$azCode',
    path: '/$azCode',
    getParentRoute: () => ApiPublicV1ProductsRoute,
  } as any)
const ApiPublicV1SuppliersWebhookRoute =
  ApiPublicV1SuppliersWebhookRouteImport.update({
    id: '/webhook',
    path: '/webhook',
    getParentRoute: () => ApiPublicV1SuppliersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ai-chat': typeof AuthenticatedAiChatRouteWithChildren
  '/ai-review': typeof AuthenticatedAiReviewRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/build-health': typeof AuthenticatedBuildHealthRoute
  '/content': typeof AuthenticatedContentRoute
  '/content-review': typeof AuthenticatedContentReviewRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/manufacturing-orders': typeof AuthenticatedManufacturingOrdersRoute
  '/product-agent': typeof AuthenticatedProductAgentRoute
  '/quote-requests': typeof AuthenticatedQuoteRequestsRoute
  '/supplier-inventory': typeof AuthenticatedSupplierInventoryRoute
  '/support': typeof AuthenticatedSupportRoute
  '/catalog/$azCode': typeof CatalogAzCodeRoute
  '/catalogs/$slug': typeof CatalogsSlugRoute
  '/catalog/': typeof CatalogIndexRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/families': typeof AuthenticatedAdminFamiliesRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/ai-chat/history': typeof AuthenticatedAiChatHistoryRoute
  '/ai-studio/bulk': typeof AuthenticatedAiStudioBulkRoute
  '/ai-studio/datasheets': typeof AuthenticatedAiStudioDatasheetsRoute
  '/ai-studio/images': typeof AuthenticatedAiStudioImagesRoute
  '/ai-studio/optimize': typeof AuthenticatedAiStudioOptimizeRoute
  '/ai-studio/quotes': typeof AuthenticatedAiStudioQuotesRoute
  '/assets/bulk-upload': typeof AuthenticatedAssetsBulkUploadRoute
  '/assets/duplicates': typeof AuthenticatedAssetsDuplicatesRoute
  '/assets/unlinked': typeof AuthenticatedAssetsUnlinkedRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/dashboard': typeof AuthenticatedProductsDashboardRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/ai-studio/': typeof AuthenticatedAiStudioIndexRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/api-center/': typeof AuthenticatedApiCenterIndexRoute
  '/approvals/': typeof AuthenticatedApprovalsIndexRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/duplicates/': typeof AuthenticatedDuplicatesIndexRoute
  '/export/': typeof AuthenticatedExportIndexRoute
  '/import/': typeof AuthenticatedImportIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/pricing/': typeof AuthenticatedPricingIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/admin/catalogs/$slug': typeof AuthenticatedAdminCatalogsSlugRoute
  '/api/agent/v1/internal-approval': typeof ApiAgentV1InternalApprovalRoute
  '/api/agent/v1/order-status': typeof ApiAgentV1OrderStatusRoute
  '/api/agent/v1/product-agent': typeof ApiAgentV1ProductAgentRoute
  '/api/agent/v1/quote-request': typeof ApiAgentV1QuoteRequestRoute
  '/api/agent/v1/quote-response': typeof ApiAgentV1QuoteResponseRoute
  '/api/public/v1/assets': typeof ApiPublicV1AssetsRoute
  '/api/public/v1/pricing': typeof ApiPublicV1PricingRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/suppliers': typeof ApiPublicV1SuppliersRouteWithChildren
  '/admin/catalogs/': typeof AuthenticatedAdminCatalogsIndexRoute
  '/api/private/v1/ai/batch-optimize': typeof ApiPrivateV1AiBatchOptimizeRoute
  '/api/private/v1/ai/generate-datasheet': typeof ApiPrivateV1AiGenerateDatasheetRoute
  '/api/private/v1/ai/job-status': typeof ApiPrivateV1AiJobStatusRoute
  '/api/private/v1/ai/optimize-product': typeof ApiPrivateV1AiOptimizeProductRoute
  '/api/public/v1/ai/quotes': typeof ApiPublicV1AiQuotesRoute
  '/api/public/v1/products/$azCode': typeof ApiPublicV1ProductsAzCodeRoute
  '/api/public/v1/suppliers/webhook': typeof ApiPublicV1SuppliersWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-chat': typeof AuthenticatedAiChatRouteWithChildren
  '/ai-review': typeof AuthenticatedAiReviewRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/build-health': typeof AuthenticatedBuildHealthRoute
  '/content': typeof AuthenticatedContentRoute
  '/content-review': typeof AuthenticatedContentReviewRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/manufacturing-orders': typeof AuthenticatedManufacturingOrdersRoute
  '/product-agent': typeof AuthenticatedProductAgentRoute
  '/quote-requests': typeof AuthenticatedQuoteRequestsRoute
  '/supplier-inventory': typeof AuthenticatedSupplierInventoryRoute
  '/support': typeof AuthenticatedSupportRoute
  '/catalog/$azCode': typeof CatalogAzCodeRoute
  '/catalogs/$slug': typeof CatalogsSlugRoute
  '/catalog': typeof CatalogIndexRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/families': typeof AuthenticatedAdminFamiliesRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/ai-chat/history': typeof AuthenticatedAiChatHistoryRoute
  '/ai-studio/bulk': typeof AuthenticatedAiStudioBulkRoute
  '/ai-studio/datasheets': typeof AuthenticatedAiStudioDatasheetsRoute
  '/ai-studio/images': typeof AuthenticatedAiStudioImagesRoute
  '/ai-studio/optimize': typeof AuthenticatedAiStudioOptimizeRoute
  '/ai-studio/quotes': typeof AuthenticatedAiStudioQuotesRoute
  '/assets/bulk-upload': typeof AuthenticatedAssetsBulkUploadRoute
  '/assets/duplicates': typeof AuthenticatedAssetsDuplicatesRoute
  '/assets/unlinked': typeof AuthenticatedAssetsUnlinkedRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/dashboard': typeof AuthenticatedProductsDashboardRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/ai-studio': typeof AuthenticatedAiStudioIndexRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/api-center': typeof AuthenticatedApiCenterIndexRoute
  '/approvals': typeof AuthenticatedApprovalsIndexRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/duplicates': typeof AuthenticatedDuplicatesIndexRoute
  '/export': typeof AuthenticatedExportIndexRoute
  '/import': typeof AuthenticatedImportIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/pricing': typeof AuthenticatedPricingIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/admin/catalogs/$slug': typeof AuthenticatedAdminCatalogsSlugRoute
  '/api/agent/v1/internal-approval': typeof ApiAgentV1InternalApprovalRoute
  '/api/agent/v1/order-status': typeof ApiAgentV1OrderStatusRoute
  '/api/agent/v1/product-agent': typeof ApiAgentV1ProductAgentRoute
  '/api/agent/v1/quote-request': typeof ApiAgentV1QuoteRequestRoute
  '/api/agent/v1/quote-response': typeof ApiAgentV1QuoteResponseRoute
  '/api/public/v1/assets': typeof ApiPublicV1AssetsRoute
  '/api/public/v1/pricing': typeof ApiPublicV1PricingRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/suppliers': typeof ApiPublicV1SuppliersRouteWithChildren
  '/admin/catalogs': typeof AuthenticatedAdminCatalogsIndexRoute
  '/api/private/v1/ai/batch-optimize': typeof ApiPrivateV1AiBatchOptimizeRoute
  '/api/private/v1/ai/generate-datasheet': typeof ApiPrivateV1AiGenerateDatasheetRoute
  '/api/private/v1/ai/job-status': typeof ApiPrivateV1AiJobStatusRoute
  '/api/private/v1/ai/optimize-product': typeof ApiPrivateV1AiOptimizeProductRoute
  '/api/public/v1/ai/quotes': typeof ApiPublicV1AiQuotesRoute
  '/api/public/v1/products/$azCode': typeof ApiPublicV1ProductsAzCodeRoute
  '/api/public/v1/suppliers/webhook': typeof ApiPublicV1SuppliersWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/ai-chat': typeof AuthenticatedAiChatRouteWithChildren
  '/_authenticated/ai-review': typeof AuthenticatedAiReviewRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/build-health': typeof AuthenticatedBuildHealthRoute
  '/_authenticated/content': typeof AuthenticatedContentRoute
  '/_authenticated/content-review': typeof AuthenticatedContentReviewRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/manufacturing-orders': typeof AuthenticatedManufacturingOrdersRoute
  '/_authenticated/product-agent': typeof AuthenticatedProductAgentRoute
  '/_authenticated/quote-requests': typeof AuthenticatedQuoteRequestsRoute
  '/_authenticated/supplier-inventory': typeof AuthenticatedSupplierInventoryRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/catalog/$azCode': typeof CatalogAzCodeRoute
  '/catalogs/$slug': typeof CatalogsSlugRoute
  '/catalog/': typeof CatalogIndexRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/families': typeof AuthenticatedAdminFamiliesRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/ai-chat/history': typeof AuthenticatedAiChatHistoryRoute
  '/_authenticated/ai-studio/bulk': typeof AuthenticatedAiStudioBulkRoute
  '/_authenticated/ai-studio/datasheets': typeof AuthenticatedAiStudioDatasheetsRoute
  '/_authenticated/ai-studio/images': typeof AuthenticatedAiStudioImagesRoute
  '/_authenticated/ai-studio/optimize': typeof AuthenticatedAiStudioOptimizeRoute
  '/_authenticated/ai-studio/quotes': typeof AuthenticatedAiStudioQuotesRoute
  '/_authenticated/assets/bulk-upload': typeof AuthenticatedAssetsBulkUploadRoute
  '/_authenticated/assets/duplicates': typeof AuthenticatedAssetsDuplicatesRoute
  '/_authenticated/assets/unlinked': typeof AuthenticatedAssetsUnlinkedRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/products/dashboard': typeof AuthenticatedProductsDashboardRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/_authenticated/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/ai-studio/': typeof AuthenticatedAiStudioIndexRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/api-center/': typeof AuthenticatedApiCenterIndexRoute
  '/_authenticated/approvals/': typeof AuthenticatedApprovalsIndexRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/duplicates/': typeof AuthenticatedDuplicatesIndexRoute
  '/_authenticated/export/': typeof AuthenticatedExportIndexRoute
  '/_authenticated/import/': typeof AuthenticatedImportIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/pricing/': typeof AuthenticatedPricingIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/_authenticated/admin/catalogs/$slug': typeof AuthenticatedAdminCatalogsSlugRoute
  '/api/agent/v1/internal-approval': typeof ApiAgentV1InternalApprovalRoute
  '/api/agent/v1/order-status': typeof ApiAgentV1OrderStatusRoute
  '/api/agent/v1/product-agent': typeof ApiAgentV1ProductAgentRoute
  '/api/agent/v1/quote-request': typeof ApiAgentV1QuoteRequestRoute
  '/api/agent/v1/quote-response': typeof ApiAgentV1QuoteResponseRoute
  '/api/public/v1/assets': typeof ApiPublicV1AssetsRoute
  '/api/public/v1/pricing': typeof ApiPublicV1PricingRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/suppliers': typeof ApiPublicV1SuppliersRouteWithChildren
  '/_authenticated/admin/catalogs/': typeof AuthenticatedAdminCatalogsIndexRoute
  '/api/private/v1/ai/batch-optimize': typeof ApiPrivateV1AiBatchOptimizeRoute
  '/api/private/v1/ai/generate-datasheet': typeof ApiPrivateV1AiGenerateDatasheetRoute
  '/api/private/v1/ai/job-status': typeof ApiPrivateV1AiJobStatusRoute
  '/api/private/v1/ai/optimize-product': typeof ApiPrivateV1AiOptimizeProductRoute
  '/api/public/v1/ai/quotes': typeof ApiPublicV1AiQuotesRoute
  '/api/public/v1/products/$azCode': typeof ApiPublicV1ProductsAzCodeRoute
  '/api/public/v1/suppliers/webhook': typeof ApiPublicV1SuppliersWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/ai-chat'
    | '/ai-review'
    | '/audit-logs'
    | '/build-health'
    | '/content'
    | '/content-review'
    | '/dashboard'
    | '/integrations'
    | '/manufacturing-orders'
    | '/product-agent'
    | '/quote-requests'
    | '/supplier-inventory'
    | '/support'
    | '/catalog/$azCode'
    | '/catalogs/$slug'
    | '/catalog/'
    | '/admin/api-keys'
    | '/admin/categories'
    | '/admin/families'
    | '/admin/integrations'
    | '/admin/units'
    | '/admin/users'
    | '/ai-chat/history'
    | '/ai-studio/bulk'
    | '/ai-studio/datasheets'
    | '/ai-studio/images'
    | '/ai-studio/optimize'
    | '/ai-studio/quotes'
    | '/assets/bulk-upload'
    | '/assets/duplicates'
    | '/assets/unlinked'
    | '/products/$id'
    | '/products/dashboard'
    | '/products/new'
    | '/requests/$id'
    | '/suppliers/$id'
    | '/admin/'
    | '/ai-studio/'
    | '/analytics/'
    | '/api-center/'
    | '/approvals/'
    | '/assets/'
    | '/duplicates/'
    | '/export/'
    | '/import/'
    | '/notifications/'
    | '/pricing/'
    | '/products/'
    | '/requests/'
    | '/settings/'
    | '/suppliers/'
    | '/admin/catalogs/$slug'
    | '/api/agent/v1/internal-approval'
    | '/api/agent/v1/order-status'
    | '/api/agent/v1/product-agent'
    | '/api/agent/v1/quote-request'
    | '/api/agent/v1/quote-response'
    | '/api/public/v1/assets'
    | '/api/public/v1/pricing'
    | '/api/public/v1/products'
    | '/api/public/v1/suppliers'
    | '/admin/catalogs/'
    | '/api/private/v1/ai/batch-optimize'
    | '/api/private/v1/ai/generate-datasheet'
    | '/api/private/v1/ai/job-status'
    | '/api/private/v1/ai/optimize-product'
    | '/api/public/v1/ai/quotes'
    | '/api/public/v1/products/$azCode'
    | '/api/public/v1/suppliers/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-chat'
    | '/ai-review'
    | '/audit-logs'
    | '/build-health'
    | '/content'
    | '/content-review'
    | '/dashboard'
    | '/integrations'
    | '/manufacturing-orders'
    | '/product-agent'
    | '/quote-requests'
    | '/supplier-inventory'
    | '/support'
    | '/catalog/$azCode'
    | '/catalogs/$slug'
    | '/catalog'
    | '/admin/api-keys'
    | '/admin/categories'
    | '/admin/families'
    | '/admin/integrations'
    | '/admin/units'
    | '/admin/users'
    | '/ai-chat/history'
    | '/ai-studio/bulk'
    | '/ai-studio/datasheets'
    | '/ai-studio/images'
    | '/ai-studio/optimize'
    | '/ai-studio/quotes'
    | '/assets/bulk-upload'
    | '/assets/duplicates'
    | '/assets/unlinked'
    | '/products/$id'
    | '/products/dashboard'
    | '/products/new'
    | '/requests/$id'
    | '/suppliers/$id'
    | '/admin'
    | '/ai-studio'
    | '/analytics'
    | '/api-center'
    | '/approvals'
    | '/assets'
    | '/duplicates'
    | '/export'
    | '/import'
    | '/notifications'
    | '/pricing'
    | '/products'
    | '/requests'
    | '/settings'
    | '/suppliers'
    | '/admin/catalogs/$slug'
    | '/api/agent/v1/internal-approval'
    | '/api/agent/v1/order-status'
    | '/api/agent/v1/product-agent'
    | '/api/agent/v1/quote-request'
    | '/api/agent/v1/quote-response'
    | '/api/public/v1/assets'
    | '/api/public/v1/pricing'
    | '/api/public/v1/products'
    | '/api/public/v1/suppliers'
    | '/admin/catalogs'
    | '/api/private/v1/ai/batch-optimize'
    | '/api/private/v1/ai/generate-datasheet'
    | '/api/private/v1/ai/job-status'
    | '/api/private/v1/ai/optimize-product'
    | '/api/public/v1/ai/quotes'
    | '/api/public/v1/products/$azCode'
    | '/api/public/v1/suppliers/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/ai-chat'
    | '/_authenticated/ai-review'
    | '/_authenticated/audit-logs'
    | '/_authenticated/build-health'
    | '/_authenticated/content'
    | '/_authenticated/content-review'
    | '/_authenticated/dashboard'
    | '/_authenticated/integrations'
    | '/_authenticated/manufacturing-orders'
    | '/_authenticated/product-agent'
    | '/_authenticated/quote-requests'
    | '/_authenticated/supplier-inventory'
    | '/_authenticated/support'
    | '/catalog/$azCode'
    | '/catalogs/$slug'
    | '/catalog/'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/families'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/units'
    | '/_authenticated/admin/users'
    | '/_authenticated/ai-chat/history'
    | '/_authenticated/ai-studio/bulk'
    | '/_authenticated/ai-studio/datasheets'
    | '/_authenticated/ai-studio/images'
    | '/_authenticated/ai-studio/optimize'
    | '/_authenticated/ai-studio/quotes'
    | '/_authenticated/assets/bulk-upload'
    | '/_authenticated/assets/duplicates'
    | '/_authenticated/assets/unlinked'
    | '/_authenticated/products/$id'
    | '/_authenticated/products/dashboard'
    | '/_authenticated/products/new'
    | '/_authenticated/requests/$id'
    | '/_authenticated/suppliers/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/ai-studio/'
    | '/_authenticated/analytics/'
    | '/_authenticated/api-center/'
    | '/_authenticated/approvals/'
    | '/_authenticated/assets/'
    | '/_authenticated/duplicates/'
    | '/_authenticated/export/'
    | '/_authenticated/import/'
    | '/_authenticated/notifications/'
    | '/_authenticated/pricing/'
    | '/_authenticated/products/'
    | '/_authenticated/requests/'
    | '/_authenticated/settings/'
    | '/_authenticated/suppliers/'
    | '/_authenticated/admin/catalogs/$slug'
    | '/api/agent/v1/internal-approval'
    | '/api/agent/v1/order-status'
    | '/api/agent/v1/product-agent'
    | '/api/agent/v1/quote-request'
    | '/api/agent/v1/quote-response'
    | '/api/public/v1/assets'
    | '/api/public/v1/pricing'
    | '/api/public/v1/products'
    | '/api/public/v1/suppliers'
    | '/_authenticated/admin/catalogs/'
    | '/api/private/v1/ai/batch-optimize'
    | '/api/private/v1/ai/generate-datasheet'
    | '/api/private/v1/ai/job-status'
    | '/api/private/v1/ai/optimize-product'
    | '/api/public/v1/ai/quotes'
    | '/api/public/v1/products/$azCode'
    | '/api/public/v1/suppliers/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  CatalogAzCodeRoute: typeof CatalogAzCodeRoute
  CatalogsSlugRoute: typeof CatalogsSlugRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  ApiAgentV1InternalApprovalRoute: typeof ApiAgentV1InternalApprovalRoute
  ApiAgentV1OrderStatusRoute: typeof ApiAgentV1OrderStatusRoute
  ApiAgentV1ProductAgentRoute: typeof ApiAgentV1ProductAgentRoute
  ApiAgentV1QuoteRequestRoute: typeof ApiAgentV1QuoteRequestRoute
  ApiAgentV1QuoteResponseRoute: typeof ApiAgentV1QuoteResponseRoute
  ApiPublicV1AssetsRoute: typeof ApiPublicV1AssetsRoute
  ApiPublicV1PricingRoute: typeof ApiPublicV1PricingRoute
  ApiPublicV1ProductsRoute: typeof ApiPublicV1ProductsRouteWithChildren
  ApiPublicV1SuppliersRoute: typeof ApiPublicV1SuppliersRouteWithChildren
  ApiPrivateV1AiBatchOptimizeRoute: typeof ApiPrivateV1AiBatchOptimizeRoute
  ApiPrivateV1AiGenerateDatasheetRoute: typeof ApiPrivateV1AiGenerateDatasheetRoute
  ApiPrivateV1AiJobStatusRoute: typeof ApiPrivateV1AiJobStatusRoute
  ApiPrivateV1AiOptimizeProductRoute: typeof ApiPrivateV1AiOptimizeProductRoute
  ApiPublicV1AiQuotesRoute: typeof ApiPublicV1AiQuotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-chat': {
      id: '/_authenticated/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AuthenticatedAiChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-review': {
      id: '/_authenticated/ai-review'
      path: '/ai-review'
      fullPath: '/ai-review'
      preLoaderRoute: typeof AuthenticatedAiReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/build-health': {
      id: '/_authenticated/build-health'
      path: '/build-health'
      fullPath: '/build-health'
      preLoaderRoute: typeof AuthenticatedBuildHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content': {
      id: '/_authenticated/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AuthenticatedContentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-review': {
      id: '/_authenticated/content-review'
      path: '/content-review'
      fullPath: '/content-review'
      preLoaderRoute: typeof AuthenticatedContentReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manufacturing-orders': {
      id: '/_authenticated/manufacturing-orders'
      path: '/manufacturing-orders'
      fullPath: '/manufacturing-orders'
      preLoaderRoute: typeof AuthenticatedManufacturingOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/product-agent': {
      id: '/_authenticated/product-agent'
      path: '/product-agent'
      fullPath: '/product-agent'
      preLoaderRoute: typeof AuthenticatedProductAgentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quote-requests': {
      id: '/_authenticated/quote-requests'
      path: '/quote-requests'
      fullPath: '/quote-requests'
      preLoaderRoute: typeof AuthenticatedQuoteRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier-inventory': {
      id: '/_authenticated/supplier-inventory'
      path: '/supplier-inventory'
      fullPath: '/supplier-inventory'
      preLoaderRoute: typeof AuthenticatedSupplierInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$azCode': {
      id: '/catalog/$azCode'
      path: '/catalog/$azCode'
      fullPath: '/catalog/$azCode'
      preLoaderRoute: typeof CatalogAzCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/$slug': {
      id: '/catalogs/$slug'
      path: '/catalogs/$slug'
      fullPath: '/catalogs/$slug'
      preLoaderRoute: typeof CatalogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/families': {
      id: '/_authenticated/admin/families'
      path: '/families'
      fullPath: '/admin/families'
      preLoaderRoute: typeof AuthenticatedAdminFamiliesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/units': {
      id: '/_authenticated/admin/units'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AuthenticatedAdminUnitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/ai-chat/history': {
      id: '/_authenticated/ai-chat/history'
      path: '/history'
      fullPath: '/ai-chat/history'
      preLoaderRoute: typeof AuthenticatedAiChatHistoryRouteImport
      parentRoute: typeof AuthenticatedAiChatRoute
    }
    '/_authenticated/ai-studio/': {
      id: '/_authenticated/ai-studio/'
      path: '/ai-studio'
      fullPath: '/ai-studio/'
      preLoaderRoute: typeof AuthenticatedAiStudioIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-studio/bulk': {
      id: '/_authenticated/ai-studio/bulk'
      path: '/ai-studio/bulk'
      fullPath: '/ai-studio/bulk'
      preLoaderRoute: typeof AuthenticatedAiStudioBulkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-studio/datasheets': {
      id: '/_authenticated/ai-studio/datasheets'
      path: '/ai-studio/datasheets'
      fullPath: '/ai-studio/datasheets'
      preLoaderRoute: typeof AuthenticatedAiStudioDatasheetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-studio/images': {
      id: '/_authenticated/ai-studio/images'
      path: '/ai-studio/images'
      fullPath: '/ai-studio/images'
      preLoaderRoute: typeof AuthenticatedAiStudioImagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-studio/optimize': {
      id: '/_authenticated/ai-studio/optimize'
      path: '/ai-studio/optimize'
      fullPath: '/ai-studio/optimize'
      preLoaderRoute: typeof AuthenticatedAiStudioOptimizeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-studio/quotes': {
      id: '/_authenticated/ai-studio/quotes'
      path: '/ai-studio/quotes'
      fullPath: '/ai-studio/quotes'
      preLoaderRoute: typeof AuthenticatedAiStudioQuotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-center/': {
      id: '/_authenticated/api-center/'
      path: '/api-center'
      fullPath: '/api-center/'
      preLoaderRoute: typeof AuthenticatedApiCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals/': {
      id: '/_authenticated/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AuthenticatedApprovalsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/bulk-upload': {
      id: '/_authenticated/assets/bulk-upload'
      path: '/assets/bulk-upload'
      fullPath: '/assets/bulk-upload'
      preLoaderRoute: typeof AuthenticatedAssetsBulkUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/duplicates': {
      id: '/_authenticated/assets/duplicates'
      path: '/assets/duplicates'
      fullPath: '/assets/duplicates'
      preLoaderRoute: typeof AuthenticatedAssetsDuplicatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/unlinked': {
      id: '/_authenticated/assets/unlinked'
      path: '/assets/unlinked'
      fullPath: '/assets/unlinked'
      preLoaderRoute: typeof AuthenticatedAssetsUnlinkedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/duplicates/': {
      id: '/_authenticated/duplicates/'
      path: '/duplicates'
      fullPath: '/duplicates/'
      preLoaderRoute: typeof AuthenticatedDuplicatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/export/': {
      id: '/_authenticated/export/'
      path: '/export'
      fullPath: '/export/'
      preLoaderRoute: typeof AuthenticatedExportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import/': {
      id: '/_authenticated/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof AuthenticatedImportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing/': {
      id: '/_authenticated/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof AuthenticatedPricingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/dashboard': {
      id: '/_authenticated/products/dashboard'
      path: '/products/dashboard'
      fullPath: '/products/dashboard'
      preLoaderRoute: typeof AuthenticatedProductsDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/$id': {
      id: '/_authenticated/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof AuthenticatedRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers/$id': {
      id: '/_authenticated/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AuthenticatedSuppliersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/catalogs/': {
      id: '/_authenticated/admin/catalogs/'
      path: '/catalogs'
      fullPath: '/admin/catalogs/'
      preLoaderRoute: typeof AuthenticatedAdminCatalogsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalogs/$slug': {
      id: '/_authenticated/admin/catalogs/$slug'
      path: '/catalogs/$slug'
      fullPath: '/admin/catalogs/$slug'
      preLoaderRoute: typeof AuthenticatedAdminCatalogsSlugRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/agent/v1/internal-approval': {
      id: '/api/agent/v1/internal-approval'
      path: '/api/agent/v1/internal-approval'
      fullPath: '/api/agent/v1/internal-approval'
      preLoaderRoute: typeof ApiAgentV1InternalApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/v1/order-status': {
      id: '/api/agent/v1/order-status'
      path: '/api/agent/v1/order-status'
      fullPath: '/api/agent/v1/order-status'
      preLoaderRoute: typeof ApiAgentV1OrderStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/v1/product-agent': {
      id: '/api/agent/v1/product-agent'
      path: '/api/agent/v1/product-agent'
      fullPath: '/api/agent/v1/product-agent'
      preLoaderRoute: typeof ApiAgentV1ProductAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/v1/quote-request': {
      id: '/api/agent/v1/quote-request'
      path: '/api/agent/v1/quote-request'
      fullPath: '/api/agent/v1/quote-request'
      preLoaderRoute: typeof ApiAgentV1QuoteRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/v1/quote-response': {
      id: '/api/agent/v1/quote-response'
      path: '/api/agent/v1/quote-response'
      fullPath: '/api/agent/v1/quote-response'
      preLoaderRoute: typeof ApiAgentV1QuoteResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/assets': {
      id: '/api/public/v1/assets'
      path: '/api/public/v1/assets'
      fullPath: '/api/public/v1/assets'
      preLoaderRoute: typeof ApiPublicV1AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/pricing': {
      id: '/api/public/v1/pricing'
      path: '/api/public/v1/pricing'
      fullPath: '/api/public/v1/pricing'
      preLoaderRoute: typeof ApiPublicV1PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products': {
      id: '/api/public/v1/products'
      path: '/api/public/v1/products'
      fullPath: '/api/public/v1/products'
      preLoaderRoute: typeof ApiPublicV1ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/suppliers': {
      id: '/api/public/v1/suppliers'
      path: '/api/public/v1/suppliers'
      fullPath: '/api/public/v1/suppliers'
      preLoaderRoute: typeof ApiPublicV1SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/v1/ai/batch-optimize': {
      id: '/api/private/v1/ai/batch-optimize'
      path: '/api/private/v1/ai/batch-optimize'
      fullPath: '/api/private/v1/ai/batch-optimize'
      preLoaderRoute: typeof ApiPrivateV1AiBatchOptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/v1/ai/generate-datasheet': {
      id: '/api/private/v1/ai/generate-datasheet'
      path: '/api/private/v1/ai/generate-datasheet'
      fullPath: '/api/private/v1/ai/generate-datasheet'
      preLoaderRoute: typeof ApiPrivateV1AiGenerateDatasheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/v1/ai/job-status': {
      id: '/api/private/v1/ai/job-status'
      path: '/api/private/v1/ai/job-status'
      fullPath: '/api/private/v1/ai/job-status'
      preLoaderRoute: typeof ApiPrivateV1AiJobStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/v1/ai/optimize-product': {
      id: '/api/private/v1/ai/optimize-product'
      path: '/api/private/v1/ai/optimize-product'
      fullPath: '/api/private/v1/ai/optimize-product'
      preLoaderRoute: typeof ApiPrivateV1AiOptimizeProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/ai/quotes': {
      id: '/api/public/v1/ai/quotes'
      path: '/api/public/v1/ai/quotes'
      fullPath: '/api/public/v1/ai/quotes'
      preLoaderRoute: typeof ApiPublicV1AiQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products/$azCode': {
      id: '/api/public/v1/products/$azCode'
      path: '/$azCode'
      fullPath: '/api/public/v1/products/$azCode'
      preLoaderRoute: typeof ApiPublicV1ProductsAzCodeRouteImport
      parentRoute: typeof ApiPublicV1ProductsRoute
    }
    '/api/public/v1/suppliers/webhook': {
      id: '/api/public/v1/suppliers/webhook'
      path: '/webhook'
      fullPath: '/api/public/v1/suppliers/webhook'
      preLoaderRoute: typeof ApiPublicV1SuppliersWebhookRouteImport
      parentRoute: typeof ApiPublicV1SuppliersRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminFamiliesRoute: typeof AuthenticatedAdminFamiliesRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminUnitsRoute: typeof AuthenticatedAdminUnitsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCatalogsSlugRoute: typeof AuthenticatedAdminCatalogsSlugRoute
  AuthenticatedAdminCatalogsIndexRoute: typeof AuthenticatedAdminCatalogsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminFamiliesRoute: AuthenticatedAdminFamiliesRoute,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminUnitsRoute: AuthenticatedAdminUnitsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCatalogsSlugRoute: AuthenticatedAdminCatalogsSlugRoute,
  AuthenticatedAdminCatalogsIndexRoute: AuthenticatedAdminCatalogsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAiChatRouteChildren {
  AuthenticatedAiChatHistoryRoute: typeof AuthenticatedAiChatHistoryRoute
}

const AuthenticatedAiChatRouteChildren: AuthenticatedAiChatRouteChildren = {
  AuthenticatedAiChatHistoryRoute: AuthenticatedAiChatHistoryRoute,
}

const AuthenticatedAiChatRouteWithChildren =
  AuthenticatedAiChatRoute._addFileChildren(AuthenticatedAiChatRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAiChatRoute: typeof AuthenticatedAiChatRouteWithChildren
  AuthenticatedAiReviewRoute: typeof AuthenticatedAiReviewRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedBuildHealthRoute: typeof AuthenticatedBuildHealthRoute
  AuthenticatedContentRoute: typeof AuthenticatedContentRoute
  AuthenticatedContentReviewRoute: typeof AuthenticatedContentReviewRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedManufacturingOrdersRoute: typeof AuthenticatedManufacturingOrdersRoute
  AuthenticatedProductAgentRoute: typeof AuthenticatedProductAgentRoute
  AuthenticatedQuoteRequestsRoute: typeof AuthenticatedQuoteRequestsRoute
  AuthenticatedSupplierInventoryRoute: typeof AuthenticatedSupplierInventoryRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedAiStudioBulkRoute: typeof AuthenticatedAiStudioBulkRoute
  AuthenticatedAiStudioDatasheetsRoute: typeof AuthenticatedAiStudioDatasheetsRoute
  AuthenticatedAiStudioImagesRoute: typeof AuthenticatedAiStudioImagesRoute
  AuthenticatedAiStudioOptimizeRoute: typeof AuthenticatedAiStudioOptimizeRoute
  AuthenticatedAiStudioQuotesRoute: typeof AuthenticatedAiStudioQuotesRoute
  AuthenticatedAssetsBulkUploadRoute: typeof AuthenticatedAssetsBulkUploadRoute
  AuthenticatedAssetsDuplicatesRoute: typeof AuthenticatedAssetsDuplicatesRoute
  AuthenticatedAssetsUnlinkedRoute: typeof AuthenticatedAssetsUnlinkedRoute
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedProductsDashboardRoute: typeof AuthenticatedProductsDashboardRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedRequestsIdRoute: typeof AuthenticatedRequestsIdRoute
  AuthenticatedSuppliersIdRoute: typeof AuthenticatedSuppliersIdRoute
  AuthenticatedAiStudioIndexRoute: typeof AuthenticatedAiStudioIndexRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedApiCenterIndexRoute: typeof AuthenticatedApiCenterIndexRoute
  AuthenticatedApprovalsIndexRoute: typeof AuthenticatedApprovalsIndexRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
  AuthenticatedDuplicatesIndexRoute: typeof AuthenticatedDuplicatesIndexRoute
  AuthenticatedExportIndexRoute: typeof AuthenticatedExportIndexRoute
  AuthenticatedImportIndexRoute: typeof AuthenticatedImportIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedPricingIndexRoute: typeof AuthenticatedPricingIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAiChatRoute: AuthenticatedAiChatRouteWithChildren,
  AuthenticatedAiReviewRoute: AuthenticatedAiReviewRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedBuildHealthRoute: AuthenticatedBuildHealthRoute,
  AuthenticatedContentRoute: AuthenticatedContentRoute,
  AuthenticatedContentReviewRoute: AuthenticatedContentReviewRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedManufacturingOrdersRoute: AuthenticatedManufacturingOrdersRoute,
  AuthenticatedProductAgentRoute: AuthenticatedProductAgentRoute,
  AuthenticatedQuoteRequestsRoute: AuthenticatedQuoteRequestsRoute,
  AuthenticatedSupplierInventoryRoute: AuthenticatedSupplierInventoryRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedAiStudioBulkRoute: AuthenticatedAiStudioBulkRoute,
  AuthenticatedAiStudioDatasheetsRoute: AuthenticatedAiStudioDatasheetsRoute,
  AuthenticatedAiStudioImagesRoute: AuthenticatedAiStudioImagesRoute,
  AuthenticatedAiStudioOptimizeRoute: AuthenticatedAiStudioOptimizeRoute,
  AuthenticatedAiStudioQuotesRoute: AuthenticatedAiStudioQuotesRoute,
  AuthenticatedAssetsBulkUploadRoute: AuthenticatedAssetsBulkUploadRoute,
  AuthenticatedAssetsDuplicatesRoute: AuthenticatedAssetsDuplicatesRoute,
  AuthenticatedAssetsUnlinkedRoute: AuthenticatedAssetsUnlinkedRoute,
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedProductsDashboardRoute: AuthenticatedProductsDashboardRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedRequestsIdRoute: AuthenticatedRequestsIdRoute,
  AuthenticatedSuppliersIdRoute: AuthenticatedSuppliersIdRoute,
  AuthenticatedAiStudioIndexRoute: AuthenticatedAiStudioIndexRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedApiCenterIndexRoute: AuthenticatedApiCenterIndexRoute,
  AuthenticatedApprovalsIndexRoute: AuthenticatedApprovalsIndexRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  AuthenticatedDuplicatesIndexRoute: AuthenticatedDuplicatesIndexRoute,
  AuthenticatedExportIndexRoute: AuthenticatedExportIndexRoute,
  AuthenticatedImportIndexRoute: AuthenticatedImportIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedPricingIndexRoute: AuthenticatedPricingIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicV1ProductsRouteChildren {
  ApiPublicV1ProductsAzCodeRoute: typeof ApiPublicV1ProductsAzCodeRoute
}

const ApiPublicV1ProductsRouteChildren: ApiPublicV1ProductsRouteChildren = {
  ApiPublicV1ProductsAzCodeRoute: ApiPublicV1ProductsAzCodeRoute,
}

const ApiPublicV1ProductsRouteWithChildren =
  ApiPublicV1ProductsRoute._addFileChildren(ApiPublicV1ProductsRouteChildren)

interface ApiPublicV1SuppliersRouteChildren {
  ApiPublicV1SuppliersWebhookRoute: typeof ApiPublicV1SuppliersWebhookRoute
}

const ApiPublicV1SuppliersRouteChildren: ApiPublicV1SuppliersRouteChildren = {
  ApiPublicV1SuppliersWebhookRoute: ApiPublicV1SuppliersWebhookRoute,
}

const ApiPublicV1SuppliersRouteWithChildren =
  ApiPublicV1SuppliersRoute._addFileChildren(ApiPublicV1SuppliersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  CatalogAzCodeRoute: CatalogAzCodeRoute,
  CatalogsSlugRoute: CatalogsSlugRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  ApiAgentV1InternalApprovalRoute: ApiAgentV1InternalApprovalRoute,
  ApiAgentV1OrderStatusRoute: ApiAgentV1OrderStatusRoute,
  ApiAgentV1ProductAgentRoute: ApiAgentV1ProductAgentRoute,
  ApiAgentV1QuoteRequestRoute: ApiAgentV1QuoteRequestRoute,
  ApiAgentV1QuoteResponseRoute: ApiAgentV1QuoteResponseRoute,
  ApiPublicV1AssetsRoute: ApiPublicV1AssetsRoute,
  ApiPublicV1PricingRoute: ApiPublicV1PricingRoute,
  ApiPublicV1ProductsRoute: ApiPublicV1ProductsRouteWithChildren,
  ApiPublicV1SuppliersRoute: ApiPublicV1SuppliersRouteWithChildren,
  ApiPrivateV1AiBatchOptimizeRoute: ApiPrivateV1AiBatchOptimizeRoute,
  ApiPrivateV1AiGenerateDatasheetRoute: ApiPrivateV1AiGenerateDatasheetRoute,
  ApiPrivateV1AiJobStatusRoute: ApiPrivateV1AiJobStatusRoute,
  ApiPrivateV1AiOptimizeProductRoute: ApiPrivateV1AiOptimizeProductRoute,
  ApiPublicV1AiQuotesRoute: ApiPublicV1AiQuotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
